[tool.poetry]
name = "cubox_exporter"
version = "0.1.0"
description = ""
authors = ["lukkun <yzww1999@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
